version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: autotroph-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - autotroph-network

  autotroph-service:
    build: .
    container_name: autotroph-service
    ports:
      - "8080:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_DATABASE=neo4j
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xmx512m -Xms256m
      # - OPENAI_API_KEY=your_openai_api_key_here
    depends_on:
      - neo4j
    networks:
      - autotroph-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  autotroph-network:
    driver: bridge
